# Generated by Django 4.2.7 on 2023-12-08 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='isComplete',
            new_name='is_complete',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='taskAssignDate',
            new_name='task_assign_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='taskDescription',
            new_name='task_description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='taskTitle',
            new_name='task_title',
        ),
    ]
